create database COP4331;

use COP4331;

CREATE TABLE User (
    ID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL DEFAULT '',
    LastName VARCHAR(50) NOT NULL DEFAULT '',
    Login VARCHAR(50) NOT NULL DEFAULT '',
    Password VARCHAR(50) NOT NULL DEFAULT '',
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE Contact (
    ID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL DEFAULT '',
    LastName VARCHAR(50) NOT NULL DEFAULT '',
    Phone VARCHAR(10) NOT NULL DEFAULT '',
    Email VARCHAR(50) NOT NULL DEFAULT '' ,
    UserID INT NOT NULL DEFAULT '0' ,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES User(UserID)
) ENGINE = InnoDB;


   
